version: "2.4"

services:
  web:
    build: .
    ports:
      - "7000:8000"
    restart: always
    tty: true

  mysql:
    image: mysql:5.7.27
    environment:
      - MYSQL_USER=alikexpress
      - MYSQL_PASSWORD=secretpass
      - MYSQL_DATABASE=alikexpress
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

volumes:
  db: